version: '3.5'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: my_database_schema
    ports:
      - "3306:3306"
    volumes:
      - "./my_sql_file.sql:/docker-entrypoint-initdb.d/1.sql"
